#!/bin/sh

# Directory listings
if [ -d "$1" ]; then
	ls -lh --color "$1"
	exit 0
fi

# From: http://petereisentraut.blogspot.com/2009/07/adding-color-to-console-code-syntax.html
#exec source-highlight -fesc -oSTDOUT "$1" 2>/dev/null
hash pygmentize 2> /dev/null && pygmentize "$1" 2> /dev/null

# Process further with lesspipe
exit 1
