# If not running interactively, don't do anything
[[ "$-" == *i* ]] || return

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export  XDG_CACHE_HOME="$HOME/.cache"
export   XDG_DATA_HOME="$HOME/.local/share"

PATH=$XDG_CONFIG_HOME/scripts:$HOME/sys/bin:/sbin:/usr/sbin:/usr/local/sbin:$PATH

# Setup colorisation for ls
eval $(dircolors -b)

#export CDPATH=".:~"
export HISTIGNORE="ls:clear"
export HISTCONTROL="ignoredups"

# Colored grep
export GREP_COLOR='1;33'

# less configuration
# * -Q: do not beep
# * -R: allow colors
# * -i: case-insensitive search
export LESS="-QRi"

# Vim, disable X support
export VISUAL="vim -X"
export EDITOR=${VISUAL}

# When using direnv, don't warn about slow execution
export DIRENV_WARN_TIMEOUT=20m

# Default web browser
export BROWSER=firefox

# Store since state file
export SINCE=$HOME/.cache/since/since

# For Debian/Ubuntu's bug reporting tool
export REPORTBUGMAIL="debian@samat.org"

# Don't add quotes when using ls
export QUOTING_STYLE=literal

# Source shellcheck configuration
hash shellcheck 2>/dev/null && source "$XDG_CONFIG_HOME/bash/shellcheck"

# Source keychain (ssh-agent and gpg-agent) environment
#  Machine is responsible for both SSH and GnuPG
if [[ -f "$HOME/.keychain/$(hostname)-sh-gpg" ]]; then
        keychain --nocolor --quiet "$HOME/.ssh/id_ed25519" "$HOME/.ssh/id_rsa" 4A456FBA
        source "$HOME/.keychain/$(hostname)-sh"
        source "$HOME/.keychain/$(hostname)-sh-gpg"
#  Machine is only responsible for SSH
elif [[ -f "$HOME/.keychain/$(hostname)-sh" ]]; then
        keychain --nocolor --quiet "$HOME/.ssh/id_ed25519" "$HOME/.ssh/id_rsa"
        source "$HOME/.keychain/$(hostname)-sh"
fi

for file in ~/.config/{shell,bash}/profile.d/*; do
    [[ -e $file ]] && . "$file"
done

[[ -r ~/.bashrc ]] && . ~/.bashrc
