#!/usr/bin/bash
{ pipx upgrade-all --include-injected --verbose; } &
{ cargo install-update --all; } &
{ uv tool upgrade --all; } &
{ npm update -g; } &
{ sudo flatpak update --system -y; } &
{ flatpak update --user -y; } &
wait
