[defaults]
# Better formatted errors, etc
stderr_callback = debug
stdout_callback = debug
# Use the stdout_callback when running ad-hoc commands
bin_ansible_callbacks = True
# List summary at end of execution w/ per-task timings
# ansible >=2.11
#callbacks_enabled = ansible.posix.profile_roles, ansible.posix.profile_tasks
callbacks_enabled = ansible.posix.profile_tasks
# Disable creating retry files
retry_files_enabled = False
# Use Python 3 if available
interpreter_python = auto
# If we gathered facts about a host before, don't do it again
gathering = smart
# Don't check host keys
host_key_checking = False
# requires ansible-mitogen package on Ubuntu >=21.04
strategy_plugins = /usr/lib/python3/dist-packages/ansible/plugins/strategy
strategy = mitogen_linear

[ssh_connection]
# Requires ansible 2.5 or later
pipelining = True
